# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.ts from the
# native-release-manifest.json published with v0.1.1. Do not hand-edit the
# version/url/sha256 fields below -- rerun the script against a release
# manifest instead. This file is the source of truth; it is mirrored into
# https://github.com/virusimmortal00/homebrew-amfaa by that repository's own
# scheduled sync workflow. See homebrew/README.md for details.
cask "amfaa" do
  arch arm: "darwin-arm64", intel: "darwin-x64"

  version "0.1.1"
  sha256 arm:   "13217107633c787cf3519e0dabc0b73e467ab607852374fd8c77c195649d7e56",
         intel: "5e51dd94e8531b25515dbc0a412c52b4078e36b94c798e8c23751b360cca153e"

  url "https://github.com/virusimmortal00/AllMyFriendsAreAgents/releases/download/v#{version}/all-my-friends-are-agents-v#{version}-#{arch}.tar.gz"
  name "All My Friends Are Agents"
  desc "Multi-agent chatroom for coding with AI models (native app)"
  homepage "https://github.com/virusimmortal00/AllMyFriendsAreAgents"

  # This is a Cask, not a Formula, specifically to avoid Homebrew's Mach-O
  # linkage-fixing pass, which every from-source Formula install runs
  # unconditionally: the published archive is a fully self-contained bundle
  # (its own pinned Node.js runtime, the audited OpenCode runtime, and a full
  # production node_modules tree), and rewriting embedded dylib IDs to this
  # bundle's deeply nested Caskroom path can overflow a vendored native
  # addon's Mach-O header padding. Casks stage files as-is with no relinking.
  #
  # The "amfaa" launcher locates its sibling active-version/versions/
  # directories relative to its own real invocation path (see
  # scripts/install-native.sh), so it must keep living in the stable
  # per-version Caskroom directory -- write an exec wrapper into
  # HOMEBREW_PREFIX/bin rather than using the `binary` stanza, which would
  # symlink it there instead. `{{staged_path}}` is expanded by Homebrew's
  # install-steps runner to this cask's actual Caskroom directory.
  postflight_steps do
    write_file "bin/amfaa", <<~SH, base: "homebrew_prefix"
      #!/bin/sh
      # AMFAA Homebrew Cask-managed launcher
      exec "{{staged_path}}/all-my-friends-are-agents/amfaa" "$@"
    SH
    set_permissions "bin/amfaa", "0755", base: "homebrew_prefix", recursive: false
  end

  uninstall delete: "#{HOMEBREW_PREFIX}/bin/amfaa"

  caveats do
    <<~EOS
      Run "amfaa" from the project directory you want agents to inspect to
      finish first-time setup. See the Quick start section of
      https://github.com/virusimmortal00/AllMyFriendsAreAgents#readme
    EOS
  end
end
